num_1=int(input("Enter first number: "))
num_2=int(input("Enter second number: "))
print("Thank you!")
print(f"{num_1} + {num_2} = {num_1 + num_2}")
print(f"{num_1} - {num_2} = {num_1 - num_2}")
print(f"{num_1} / {num_2} = {num_1 / num_2}")
print(f"{num_1} * {num_2} = {num_1 * num_2}")